
import React, { createContext, useContext, ReactNode, useState, useEffect } from 'react';
import { I18nManager } from 'react-native';

type SupportedLanguage = 'en' | 'mn' | 'ru' | 'kk' | 'uz' | 'uk' | 'fa';

interface LanguageContextType {
  t: (key: string) => string;
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  isRTL: boolean;
}

interface LanguageProviderProps {
  children: ReactNode;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    welcome: 'Welcome to',
    welcomeSmall: '',
    searchAttractions: 'Search attractions...',
    selectCity: 'Select City',
    closestToYou: 'Closest to you',
    noCitiesFound: 'No cities found',
    selectCityFirst: 'Select a city first',
    exploreAttractions: 'Explore Attractions',
    popularAttractions: 'Popular Attractions',
    forbiddenCity: 'Forbidden City',
    summerPalace: 'Summer Palace',
    greatWall: 'Great Wall',
    templeOfHeaven: 'Temple of Heaven',
    theBund: 'The Bund',
    yuGarden: 'Yu Garden',
    orientalPearlTower: 'Oriental Pearl Tower',
    victoriaHarbour: 'Victoria Harbour',
    victoriasPeak: 'Victoria\'s Peak',
    templeSt: 'Temple Street',
    enableLocation: 'Enable Location',
    allowLocationAccess: 'Allow location access to automatically find the nearest city',
    gettingYourLocation: 'Getting your location...',
    accountSettings: 'Account Settings',
    editProfile: 'Edit Profile',
    notifications: 'Notifications',
    privacySecurity: 'Privacy & Security',
    preferences: 'Preferences',
    language: 'Language',
    darkMode: 'Dark Mode',
    signOut: 'Sign Out',
    cities: 'Cities',
    home: 'Home',
    profile: 'Profile',
    services: 'Services',
    noAttractionsFound: 'No attractions found',
    historicalSite: 'Historical Site',
    culturalLandmark: 'Cultural Landmark',
    scenicSpot: 'Scenic Spot',
    modernAttraction: 'Modern Attraction',
    attractions: 'Attractions',
    foodAndDrinks: 'Food & Drinks',
    quickActions: 'Quick Actions',
    weatherForecast: 'Weather Forecast',
    checkLocalWeather: 'Check local weather conditions',
    transportation: 'Transportation',
    findNearbyTransit: 'Find nearby transit options',
    languageAssistant: 'Language Assistant',
    translateEasily: 'Translate and communicate easily',
    eSIM: 'eSIM',
    stayConnected: 'Stay connected locally',
    payment: 'Payment',
    securePayment: 'Secure payment options',
    guide: 'Guide',
    exploreLocal: 'Explore local attractions',
    emergency: 'Emergency',
    quickEmergency: 'Quick emergency access',
    mapsNotSupported: 'Maps are not supported in Natively web preview',
    noAttractionsAvailable: 'No attractions available',
    // Nominative case (for selection lists)
    beijing: 'Beijing',
    shanghai: 'Shanghai',
    hongKong: 'Hong Kong',
    hohhot: 'Hohhot',
    ordos: 'Ordos',
    macao: 'Macao',
    // Dative case (for titles)
    beijingDative: 'Beijing',
    shanghaiDative: 'Shanghai',
    hongKongDative: 'Hong Kong',
    hohhotDative: 'Hohhot',
    ordosDative: 'Ordos',
    macaoDative: 'Macao',
    servicesDescription: 'Access essential services for your journey',
    essentialServices: 'Essential Services',
    convenienceServices: 'Convenience Services',
    supportServices: 'Support Services',
    currencyExchange: 'Currency Exchange',
    convertCurrency: 'Convert currency easily',
    healthServices: 'Health Services',
    findMedicalHelp: 'Find medical help nearby',
    accommodation: 'Accommodation',
    findPlaceToStay: 'Find a place to stay',
    dining: 'Dining',
    discoverRestaurants: 'Discover local restaurants',
    visaInfo: 'Visa Information',
    visaRequirements: 'Check visa requirements',
    onlineConsultation: 'Online Consultation',
    consultDoctorOnline: 'Consult with doctors online',
    buyMedicine: 'Buy Medicine',
    orderMedicineOnline: 'Order medicine online',
    beijingProvince: 'Beijing',
    shanghaiProvince: 'Shanghai',
    hongKongProvince: 'Hong Kong SAR',
    macaoProvince: 'Macao SAR',
    hohhotProvince: 'Inner Mongolia',
    ordosProvince: 'Inner Mongolia',
    theme: 'Theme',
    autoTheme: 'Auto',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    autoThemeDescription: 'Light during day, dark at night',
    lightThemeDescription: 'Always use light theme',
    darkThemeDescription: 'Always use dark theme',
    selectCityToViewInfo: 'Select a city to view information',
  },
  mn: {
    welcome: '',
    welcomeSmall: 'ТАВТАЙ МОРИЛНО УУ',
    searchAttractions: 'Үзвэрийн газар хайх...',
    selectCity: 'Хот сонгох',
    closestToYou: 'Танд хамгийн ойр',
    noCitiesFound: 'Хот олдсонгүй',
    selectCityFirst: 'Эхлээд хот сонгоно уу',
    exploreAttractions: 'Үзвэрийн газруудыг судлах',
    popularAttractions: 'Алдартай үзвэрийн газрууд',
    forbiddenCity: 'Хориотой хот',
    summerPalace: 'Зуны ордон',
    greatWall: 'Их хана',
    templeOfHeaven: 'Тэнгэрийн сүм',
    theBund: 'Бунд',
    yuGarden: 'Юй цэцэрлэг',
    orientalPearlTower: 'Дорнын сувдан цамхаг',
    victoriaHarbour: 'Викториягийн боомт',
    victoriasPeak: 'Викториягийн оргил',
    templeSt: 'Сүмийн гудамж',
    enableLocation: 'Байршил идэвхжүүлэх',
    allowLocationAccess: 'Хамгийн ойрын хотыг автоматаар олохын тулд байршлын хандалтыг зөвшөөрнө үү',
    gettingYourLocation: 'Таны байршлыг авч байна...',
    accountSettings: 'Дансны тохиргоо',
    editProfile: 'Профайл засах',
    notifications: 'Мэдэгдэл',
    privacySecurity: 'Нууцлал ба аюулгүй байдал',
    preferences: 'Тохиргоо',
    language: 'Хэл',
    darkMode: 'Харанхуй горим',
    signOut: 'Гарах',
    cities: 'Хотууд',
    home: 'Нүүр',
    profile: 'Профайл',
    services: 'Үйлчилгээ',
    noAttractionsFound: 'Үзвэрийн газар олдсонгүй',
    historicalSite: 'Түүхийн дурсгалт газар',
    culturalLandmark: 'Соёлын дурсгалт газар',
    scenicSpot: 'Үзэсгэлэнт газар',
    modernAttraction: 'Орчин үеийн үзвэрийн газар',
    attractions: 'Үзвэрийн газрууд',
    foodAndDrinks: 'Хоол ба ундаа',
    quickActions: 'Шуурхай үйлдэл',
    weatherForecast: 'Цаг агаарын урьдчилсан мэдээ',
    checkLocalWeather: 'Орон нутгийн цаг агаарын нөхцлийг шалгах',
    transportation: 'Тээвэр',
    findNearbyTransit: 'Ойролцоох тээврийн хэрэгслийг олох',
    languageAssistant: 'Хэлний туслах',
    translateEasily: 'Орчуулах ба амархан харилцах',
    eSIM: 'eSIM',
    stayConnected: 'Орон нутагт холбогдсон байх',
    payment: 'Төлбөр',
    securePayment: 'Аюулгүй төлбөрийн сонголт',
    guide: 'Хөтөч',
    exploreLocal: 'Орон нутгийн үзвэрийн газруудыг судлах',
    emergency: 'Яаралтай',
    quickEmergency: 'Яаралтай тусламжийн шуурхай хандалт',
    mapsNotSupported: 'Газрын зураг Natively вэб урьдчилан үзэхэд дэмжигдэхгүй байна',
    noAttractionsAvailable: 'Үзвэрийн газар байхгүй байна',
    // Nominative case (for selection lists)
    beijing: 'Бээжин',
    shanghai: 'Шанхай',
    hongKong: 'Хонконг',
    hohhot: 'Хөххот',
    ordos: 'Ордос',
    macao: 'Макао',
    // Dative case (for titles)
    beijingDative: 'Бээжинд',
    shanghaiDative: 'Шанхайд',
    hongKongDative: 'Хонконгт',
    hohhotDative: 'Хөххотт',
    ordosDative: 'Ордост',
    macaoDative: 'Макаод',
    servicesDescription: 'Таны аялалд зайлшгүй шаардлагатай үйлчилгээнд хандах',
    essentialServices: 'Зайлшгүй үйлчилгээ',
    convenienceServices: 'Тав тухтай үйлчилгээ',
    supportServices: 'Дэмжлэгийн үйлчилгээ',
    currencyExchange: 'Валют солилцоо',
    convertCurrency: 'Валют амархан солих',
    healthServices: 'Эрүүл мэндийн үйлчилгээ',
    findMedicalHelp: 'Ойролцоох эмнэлгийн тусламж олох',
    accommodation: 'Байр',
    findPlaceToStay: 'Байрлах газар олох',
    dining: 'Хоол',
    discoverRestaurants: 'Орон нутгийн ресторан олох',
    visaInfo: 'Визний мэдээлэл',
    visaRequirements: 'Визний шаардлагыг шалгах',
    onlineConsultation: 'Онлайн зөвлөгөө',
    consultDoctorOnline: 'Эмч нартай онлайнаар зөвлөлдөх',
    buyMedicine: 'Эм худалдаж авах',
    orderMedicineOnline: 'Эмийг онлайнаар захиалах',
    beijingProvince: 'Бээжин',
    shanghaiProvince: 'Шанхай',
    hongKongProvince: 'Хонконг ТЗОА',
    macaoProvince: 'Макао ТЗОА',
    hohhotProvince: 'Өвөр Монгол',
    ordosProvince: 'Өвөр Монгол',
    theme: 'Загвар',
    autoTheme: 'Автомат',
    lightTheme: 'Цайвар',
    darkTheme: 'Харанхуй',
    autoThemeDescription: 'Өдөр цайвар, шөнө харанхуй',
    lightThemeDescription: 'Үргэлж цайвар загвар ашиглах',
    darkThemeDescription: 'Үргэлж харанхуй загвар ашиглах',
    selectCityToViewInfo: 'Мэдээлэл харахын тулд хот сонгоно уу',
  },
  ru: {
    welcome: 'Добро пожаловать в',
    welcomeSmall: '',
    searchAttractions: 'Поиск достопримечательностей...',
    selectCity: 'Выбрать город',
    closestToYou: 'Ближайший к вам',
    noCitiesFound: 'Города не найдены',
    selectCityFirst: 'Сначала выберите город',
    exploreAttractions: 'Исследовать достопримечательности',
    popularAttractions: 'Популярные достопримечательности',
    forbiddenCity: 'Запретный город',
    summerPalace: 'Летний дворец',
    greatWall: 'Великая стена',
    templeOfHeaven: 'Храм Неба',
    theBund: 'Набережная Вайтань',
    yuGarden: 'Сад Юй',
    orientalPearlTower: 'Башня Восточная жемчужина',
    victoriaHarbour: 'Гавань Виктория',
    victoriasPeak: 'Пик Виктория',
    templeSt: 'Храмовая улица',
    enableLocation: 'Включить геолокацию',
    allowLocationAccess: 'Разрешите доступ к местоположению для автоматического поиска ближайшего города',
    gettingYourLocation: 'Определение вашего местоположения...',
    accountSettings: 'Настройки аккаунта',
    editProfile: 'Редактировать профиль',
    notifications: 'Уведомления',
    privacySecurity: 'Конфиденциальность и безопасность',
    preferences: 'Настройки',
    language: 'Язык',
    darkMode: 'Темный режим',
    signOut: 'Выйти',
    cities: 'Города',
    home: 'Главная',
    profile: 'Профиль',
    services: 'Услуги',
    noAttractionsFound: 'Достопримечательности не найдены',
    historicalSite: 'Исторический объект',
    culturalLandmark: 'Культурная достопримечательность',
    scenicSpot: 'Живописное место',
    modernAttraction: 'Современная достопримечательность',
    attractions: 'Достопримечательности',
    foodAndDrinks: 'Еда и напитки',
    quickActions: 'Быстрые действия',
    weatherForecast: 'Прогноз погоды',
    checkLocalWeather: 'Проверить местную погоду',
    transportation: 'Транспорт',
    findNearbyTransit: 'Найти ближайший транспорт',
    languageAssistant: 'Языковой помощник',
    translateEasily: 'Легко переводить и общаться',
    eSIM: 'eSIM',
    stayConnected: 'Оставайтесь на связи',
    payment: 'Оплата',
    securePayment: 'Безопасные способы оплаты',
    guide: 'Гид',
    exploreLocal: 'Исследовать местные достопримечательности',
    emergency: 'Экстренная помощь',
    quickEmergency: 'Быстрый доступ к экстренным службам',
    mapsNotSupported: 'Карты не поддерживаются в веб-превью Natively',
    noAttractionsAvailable: 'Достопримечательности недоступны',
    // Nominative case (for selection lists)
    beijing: 'Пекин',
    shanghai: 'Шанхай',
    hongKong: 'Гонконг',
    hohhot: 'Хух-Хото',
    ordos: 'Ордос',
    macao: 'Макао',
    // Dative case (for titles)
    beijingDative: 'Пекин',
    shanghaiDative: 'Шанхай',
    hongKongDative: 'Гонконг',
    hohhotDative: 'Хух-Хото',
    ordosDative: 'Ордос',
    macaoDative: 'Макао',
    servicesDescription: 'Доступ к основным услугам для вашего путешествия',
    essentialServices: 'Основные услуги',
    convenienceServices: 'Удобные услуги',
    supportServices: 'Услуги поддержки',
    currencyExchange: 'Обмен валюты',
    convertCurrency: 'Легко конвертировать валюту',
    healthServices: 'Медицинские услуги',
    findMedicalHelp: 'Найти медицинскую помощь поблизости',
    accommodation: 'Жилье',
    findPlaceToStay: 'Найти место для проживания',
    dining: 'Питание',
    discoverRestaurants: 'Открыть местные рестораны',
    visaInfo: 'Визовая информация',
    visaRequirements: 'Проверить визовые требования',
    onlineConsultation: 'Онлайн-консультация',
    consultDoctorOnline: 'Консультация с врачами онлайн',
    buyMedicine: 'Купить лекарства',
    orderMedicineOnline: 'Заказать лекарства онлайн',
    beijingProvince: 'Пекин',
    shanghaiProvince: 'Шанхай',
    hongKongProvince: 'Гонконг САР',
    macaoProvince: 'Макао САР',
    hohhotProvince: 'Внутренняя Монголия',
    ordosProvince: 'Внутренняя Монголия',
    theme: 'Тема',
    autoTheme: 'Авто',
    lightTheme: 'Светлая',
    darkTheme: 'Темная',
    autoThemeDescription: 'Светлая днем, темная ночью',
    lightThemeDescription: 'Всегда использовать светлую тему',
    darkThemeDescription: 'Всегда использовать темную тему',
    selectCityToViewInfo: 'Выберите город для просмотра информации',
  },
  kk: {
    welcome: '',
    welcomeSmall: 'Қош келдіңіз',
    searchAttractions: 'Көрікті жерлерді іздеу...',
    selectCity: 'Қаланы таңдау',
    closestToYou: 'Сізге ең жақын',
    noCitiesFound: 'Қалалар табылмады',
    selectCityFirst: 'Алдымен қаланы таңдаңыз',
    exploreAttractions: 'Көрікті жерлерді зерттеу',
    popularAttractions: 'Танымал көрікті жерлер',
    forbiddenCity: 'Тыйым салынған қала',
    summerPalace: 'Жазғы сарай',
    greatWall: 'Ұлы қорған',
    templeOfHeaven: 'Аспан ғибадатханасы',
    theBund: 'Бунд',
    yuGarden: 'Юй бағы',
    orientalPearlTower: 'Шығыс інжу мұнарасы',
    victoriaHarbour: 'Виктория айлағы',
    victoriasPeak: 'Виктория шыңы',
    templeSt: 'Ғибадатхана көшесі',
    enableLocation: 'Орынды қосу',
    allowLocationAccess: 'Ең жақын қаланы автоматты түрде табу үшін орынға қолжетімділікке рұқсат беріңіз',
    gettingYourLocation: 'Сіздің орныңызды анықтау...',
    accountSettings: 'Аккаунт параметрлері',
    editProfile: 'Профильді өңдеу',
    notifications: 'Хабарландырулар',
    privacySecurity: 'Құпиялылық және қауіпсіздік',
    preferences: 'Параметрлер',
    language: 'Тіл',
    darkMode: 'Қараңғы режим',
    signOut: 'Шығу',
    cities: 'Қалалар',
    home: 'Басты бет',
    profile: 'Профиль',
    services: 'Қызметтер',
    noAttractionsFound: 'Көрікті жерлер табылмады',
    historicalSite: 'Тарихи орын',
    culturalLandmark: 'Мәдени ескерткіш',
    scenicSpot: 'Көрікті жер',
    modernAttraction: 'Заманауи көрікті жер',
    attractions: 'Көрікті жерлер',
    foodAndDrinks: 'Тамақ және сусындар',
    quickActions: 'Жылдам әрекеттер',
    weatherForecast: 'Ауа райы болжамы',
    checkLocalWeather: 'Жергілікті ауа райын тексеру',
    transportation: 'Көлік',
    findNearbyTransit: 'Жақын маңдағы көлікті табу',
    languageAssistant: 'Тіл көмекшісі',
    translateEasily: 'Оңай аудару және қарым-қатынас жасау',
    eSIM: 'eSIM',
    stayConnected: 'Байланыста болыңыз',
    payment: 'Төлем',
    securePayment: 'Қауіпсіз төлем опциялары',
    guide: 'Гид',
    exploreLocal: 'Жергілікті көрікті жерлерді зерттеу',
    emergency: 'Төтенше жағдай',
    quickEmergency: 'Төтенше қызметтерге жылдам қол жеткізу',
    mapsNotSupported: 'Карталар Natively веб алдын ала қарауда қолдау көрсетілмейді',
    noAttractionsAvailable: 'Көрікті жерлер қолжетімді емес',
    // Nominative case (for selection lists)
    beijing: 'Бейжің',
    shanghai: 'Шанхай',
    hongKong: 'Гонконг',
    hohhot: 'Хух-Хото',
    ordos: 'Ордос',
    macao: 'Макао',
    // Dative case (for titles)
    beijingDative: 'Бейжіңге',
    shanghaiDative: 'Шанхайға',
    hongKongDative: 'Гонконгқа',
    hohhotDative: 'Хух-Хотоға',
    ordosDative: 'Ордосқа',
    macaoDative: 'Макаоға',
    servicesDescription: 'Сапарыңыз үшін қажетті қызметтерге қол жеткізу',
    essentialServices: 'Қажетті қызметтер',
    convenienceServices: 'Ыңғайлы қызметтер',
    supportServices: 'Қолдау қызметтері',
    currencyExchange: 'Валюта айырбасы',
    convertCurrency: 'Валютаны оңай айырбастау',
    healthServices: 'Денсаулық сақтау қызметтері',
    findMedicalHelp: 'Жақын маңдағы медициналық көмекті табу',
    accommodation: 'Тұрғын үй',
    findPlaceToStay: 'Тұру үшін орын табу',
    dining: 'Тамақтану',
    discoverRestaurants: 'Жергілікті мейрамханаларды табу',
    visaInfo: 'Виза туралы ақпарат',
    visaRequirements: 'Виза талаптарын тексеру',
    onlineConsultation: 'Онлайн кеңес',
    consultDoctorOnline: 'Дәрігерлермен онлайн кеңес алу',
    buyMedicine: 'Дәрі сатып алу',
    orderMedicineOnline: 'Дәріні онлайн тапсырыс беру',
    beijingProvince: 'Бейжің',
    shanghaiProvince: 'Шанхай',
    hongKongProvince: 'Гонконг АӘА',
    macaoProvince: 'Макао АӘА',
    hohhotProvince: 'Ішкі Моңғолия',
    ordosProvince: 'Ішкі Моңғолия',
    theme: 'Тақырып',
    autoTheme: 'Авто',
    lightTheme: 'Ашық',
    darkTheme: 'Қараңғы',
    autoThemeDescription: 'Күндіз ашық, түнде қараңғы',
    lightThemeDescription: 'Әрқашан ашық тақырыпты пайдалану',
    darkThemeDescription: 'Әрқашан қараңғы тақырыпты пайдалану',
    selectCityToViewInfo: 'Ақпаратты көру үшін қаланы таңдаңыз',
  },
  uz: {
    welcome: '',
    welcomeSmall: 'Xush kelibsiz',
    searchAttractions: 'Diqqatga sazovor joylarni qidirish...',
    selectCity: 'Shaharni tanlang',
    closestToYou: 'Sizga eng yaqin',
    noCitiesFound: 'Shaharlar topilmadi',
    selectCityFirst: 'Avval shaharni tanlang',
    exploreAttractions: 'Diqqatga sazovor joylarni oʻrganing',
    popularAttractions: 'Mashhur diqqatga sazovor joylar',
    forbiddenCity: 'Taqiqlangan shahar',
    summerPalace: 'Yozgi saroy',
    greatWall: 'Buyuk devor',
    templeOfHeaven: 'Osmon ibodatxonasi',
    theBund: 'Bund',
    yuGarden: 'Yu bogʻi',
    orientalPearlTower: 'Sharq marvarid minorasi',
    victoriaHarbour: 'Viktoriya bandargoh',
    victoriasPeak: 'Viktoriya choʻqqisi',
    templeSt: 'Ibodatxona koʻchasi',
    enableLocation: 'Joylashuvni yoqish',
    allowLocationAccess: 'Eng yaqin shaharni avtomatik topish uchun joylashuvga ruxsat bering',
    gettingYourLocation: 'Joylashuvingizni aniqlash...',
    accountSettings: 'Hisob sozlamalari',
    editProfile: 'Profilni tahrirlash',
    notifications: 'Bildirishnomalar',
    privacySecurity: 'Maxfiylik va xavfsizlik',
    preferences: 'Sozlamalar',
    language: 'Til',
    darkMode: 'Qorongʻi rejim',
    signOut: 'Chiqish',
    cities: 'Shaharlar',
    home: 'Bosh sahifa',
    profile: 'Profil',
    services: 'Xizmatlar',
    noAttractionsFound: 'Diqqatga sazovor joylar topilmadi',
    historicalSite: 'Tarixiy joy',
    culturalLandmark: 'Madaniy yodgorlik',
    scenicSpot: 'Goʻzal joy',
    modernAttraction: 'Zamonaviy diqqatga sazovor joy',
    attractions: 'Diqqatga sazovor joylar',
    foodAndDrinks: 'Ovqat va ichimliklar',
    quickActions: 'Tez harakatlar',
    weatherForecast: 'Ob-havo prognozi',
    checkLocalWeather: 'Mahalliy ob-havoni tekshirish',
    transportation: 'Transport',
    findNearbyTransit: 'Yaqin atrofdagi transportni topish',
    languageAssistant: 'Til yordamchisi',
    translateEasily: 'Oson tarjima qilish va muloqot qilish',
    eSIM: 'eSIM',
    stayConnected: 'Aloqada qoling',
    payment: 'Toʻlov',
    securePayment: 'Xavfsiz toʻlov variantlari',
    guide: 'Qoʻllanma',
    exploreLocal: 'Mahalliy diqqatga sazovor joylarni oʻrganing',
    emergency: 'Favqulodda holat',
    quickEmergency: 'Favqulodda xizmatlarga tez kirish',
    mapsNotSupported: 'Xaritalar Natively veb koʻrinishida qoʻllab-quvvatlanmaydi',
    noAttractionsAvailable: 'Diqqatga sazovor joylar mavjud emas',
    // Nominative case (for selection lists)
    beijing: 'Pekin',
    shanghai: 'Shanxay',
    hongKong: 'Gonkong',
    hohhot: 'Xux-Xoto',
    ordos: 'Ordos',
    macao: 'Makao',
    // Dative case (for titles)
    beijingDative: 'Pekinga',
    shanghaiDative: 'Shanxayga',
    hongKongDative: 'Gonkongga',
    hohhotDative: 'Xux-Xotoga',
    ordosDative: 'Ordosga',
    macaoDative: 'Makaoga',
    servicesDescription: 'Sayohatingiz uchun zarur xizmatlarga kirish',
    essentialServices: 'Zarur xizmatlar',
    convenienceServices: 'Qulay xizmatlar',
    supportServices: 'Qoʻllab-quvvatlash xizmatlari',
    currencyExchange: 'Valyuta almashinuvi',
    convertCurrency: 'Valyutani oson almashtirish',
    healthServices: 'Sogʻliqni saqlash xizmatlari',
    findMedicalHelp: 'Yaqin atrofdagi tibbiy yordamni topish',
    accommodation: 'Turar joy',
    findPlaceToStay: 'Qolish uchun joy topish',
    dining: 'Ovqatlanish',
    discoverRestaurants: 'Mahalliy restoranlarni kashf eting',
    visaInfo: 'Viza maʼlumoti',
    visaRequirements: 'Viza talablarini tekshirish',
    onlineConsultation: 'Onlayn konsultatsiya',
    consultDoctorOnline: 'Shifokorlar bilan onlayn maslahatlashish',
    buyMedicine: 'Dori sotib olish',
    orderMedicineOnline: 'Dorini onlayn buyurtma qilish',
    beijingProvince: 'Pekin',
    shanghaiProvince: 'Shanxay',
    hongKongProvince: 'Gonkong MAH',
    macaoProvince: 'Makao MAH',
    hohhotProvince: 'Ichki Moʻgʻuliston',
    ordosProvince: 'Ichki Moʻgʻuliston',
    theme: 'Mavzu',
    autoTheme: 'Avto',
    lightTheme: 'Yorugʻ',
    darkTheme: 'Qorongʻi',
    autoThemeDescription: 'Kunduz yorugʻ, kechasi qorongʻi',
    lightThemeDescription: 'Doim yorugʻ mavzudan foydalanish',
    darkThemeDescription: 'Doim qorongʻi mavzudan foydalanish',
    selectCityToViewInfo: 'Maʼlumotni koʻrish uchun shaharni tanlang',
  },
  uk: {
    welcome: 'Ласкаво просимо до',
    welcomeSmall: '',
    searchAttractions: 'Пошук визначних місць...',
    selectCity: 'Вибрати місто',
    closestToYou: 'Найближче до вас',
    noCitiesFound: 'Міста не знайдено',
    selectCityFirst: 'Спочатку виберіть місто',
    exploreAttractions: 'Дослідити визначні місця',
    popularAttractions: 'Популярні визначні місця',
    forbiddenCity: 'Заборонене місто',
    summerPalace: 'Літній палац',
    greatWall: 'Велика стіна',
    templeOfHeaven: 'Храм Неба',
    theBund: 'Набережна Вайтань',
    yuGarden: 'Сад Юй',
    orientalPearlTower: 'Вежа Східна перлина',
    victoriaHarbour: 'Гавань Вікторія',
    victoriasPeak: 'Пік Вікторія',
    templeSt: 'Храмова вулиця',
    enableLocation: 'Увімкнути геолокацію',
    allowLocationAccess: 'Дозвольте доступ до місцезнаходження для автоматичного пошуку найближчого міста',
    gettingYourLocation: 'Визначення вашого місцезнаходження...',
    accountSettings: 'Налаштування облікового запису',
    editProfile: 'Редагувати профіль',
    notifications: 'Сповіщення',
    privacySecurity: 'Конфіденційність і безпека',
    preferences: 'Налаштування',
    language: 'Мова',
    darkMode: 'Темний режим',
    signOut: 'Вийти',
    cities: 'Міста',
    home: 'Головна',
    profile: 'Профіль',
    services: 'Послуги',
    noAttractionsFound: 'Визначні місця не знайдено',
    historicalSite: 'Історична пам\'ятка',
    culturalLandmark: 'Культурна пам\'ятка',
    scenicSpot: 'Мальовниче місце',
    modernAttraction: 'Сучасна визначна пам\'ятка',
    attractions: 'Визначні місця',
    foodAndDrinks: 'Їжа та напої',
    quickActions: 'Швидкі дії',
    weatherForecast: 'Прогноз погоди',
    checkLocalWeather: 'Перевірити місцеву погоду',
    transportation: 'Транспорт',
    findNearbyTransit: 'Знайти найближчий транспорт',
    languageAssistant: 'Мовний помічник',
    translateEasily: 'Легко перекладати та спілкуватися',
    eSIM: 'eSIM',
    stayConnected: 'Залишайтеся на зв\'язку',
    payment: 'Оплата',
    securePayment: 'Безпечні способи оплати',
    guide: 'Гід',
    exploreLocal: 'Досліджувати місцеві визначні місця',
    emergency: 'Екстрена допомога',
    quickEmergency: 'Швидкий доступ до екстрених служб',
    mapsNotSupported: 'Карти не підтримуються в веб-перегляді Natively',
    noAttractionsAvailable: 'Визначні місця недоступні',
    // Nominative case (for selection lists)
    beijing: 'Пекін',
    shanghai: 'Шанхай',
    hongKong: 'Гонконг',
    hohhot: 'Хух-Хото',
    ordos: 'Ордос',
    macao: 'Макао',
    // Genitive case (for titles) - Updated to use genitive instead of dative
    beijingDative: 'Пекіна',
    shanghaiDative: 'Шанхая',
    hongKongDative: 'Гонконга',
    hohhotDative: 'Хух-Хото',
    ordosDative: 'Ордоса',
    macaoDative: 'Макао',
    servicesDescription: 'Доступ до основних послуг для вашої подорожі',
    essentialServices: 'Основні послуги',
    convenienceServices: 'Зручні послуги',
    supportServices: 'Послуги підтримки',
    currencyExchange: 'Обмін валюти',
    convertCurrency: 'Легко конвертувати валюту',
    healthServices: 'Медичні послуги',
    findMedicalHelp: 'Знайти медичну допомогу поблизу',
    accommodation: 'Житло',
    findPlaceToStay: 'Знайти місце для проживання',
    dining: 'Харчування',
    discoverRestaurants: 'Відкрити місцеві ресторани',
    visaInfo: 'Візова інформація',
    visaRequirements: 'Перевірити візові вимоги',
    onlineConsultation: 'Онлайн-консультація',
    consultDoctorOnline: 'Консультація з лікарями онлайн',
    buyMedicine: 'Купити ліки',
    orderMedicineOnline: 'Замовити ліки онлайн',
    beijingProvince: 'Пекін',
    shanghaiProvince: 'Шанхай',
    hongKongProvince: 'Гонконг САР',
    macaoProvince: 'Макао САР',
    hohhotProvince: 'Внутрішня Монголія',
    ordosProvince: 'Внутрішня Монголія',
    theme: 'Тема',
    autoTheme: 'Авто',
    lightTheme: 'Світла',
    darkTheme: 'Темна',
    autoThemeDescription: 'Світла вдень, темна вночі',
    lightThemeDescription: 'Завжди використовувати світлу тему',
    darkThemeDescription: 'Завжди використовувати темну тему',
    selectCityToViewInfo: 'Виберіть місто для перегляду інформації',
  },
  fa: {
    welcome: 'خوش آمدید به',
    welcomeSmall: '',
    searchAttractions: 'جستجوی جاذبه‌ها...',
    selectCity: 'انتخاب شهر',
    closestToYou: 'نزدیک‌ترین به شما',
    noCitiesFound: 'شهری یافت نشد',
    selectCityFirst: 'ابتدا شهری را انتخاب کنید',
    exploreAttractions: 'کاوش جاذبه‌ها',
    popularAttractions: 'جاذبه‌های محبوب',
    forbiddenCity: 'شهر ممنوعه',
    summerPalace: 'کاخ تابستانی',
    greatWall: 'دیوار بزرگ',
    templeOfHeaven: 'معبد بهشت',
    theBund: 'باند',
    yuGarden: 'باغ یو',
    orientalPearlTower: 'برج مروارید شرقی',
    victoriaHarbour: 'بندر ویکتوریا',
    victoriasPeak: 'قله ویکتوریا',
    templeSt: 'خیابان معبد',
    enableLocation: 'فعال‌سازی موقعیت مکانی',
    allowLocationAccess: 'برای یافتن خودکار نزدیک‌ترین شهر، دسترسی به موقعیت مکانی را مجاز کنید',
    gettingYourLocation: 'در حال تعیین موقعیت شما...',
    accountSettings: 'تنظیمات حساب',
    editProfile: 'ویرایش پروفایل',
    notifications: 'اعلان‌ها',
    privacySecurity: 'حریم خصوصی و امنیت',
    preferences: 'تنظیمات',
    language: 'زبان',
    darkMode: 'حالت تاریک',
    signOut: 'خروج',
    cities: 'شهرها',
    home: 'خانه',
    profile: 'پروفایل',
    services: 'خدمات',
    noAttractionsFound: 'جاذبه‌ای یافت نشد',
    historicalSite: 'مکان تاریخی',
    culturalLandmark: 'نشانه فرهنگی',
    scenicSpot: 'مکان دیدنی',
    modernAttraction: 'جاذبه مدرن',
    attractions: 'جاذبه‌ها',
    foodAndDrinks: 'غذا و نوشیدنی',
    quickActions: 'اقدامات سریع',
    weatherForecast: 'پیش‌بینی آب و هوا',
    checkLocalWeather: 'بررسی آب و هوای محلی',
    transportation: 'حمل و نقل',
    findNearbyTransit: 'یافتن حمل و نقل نزدیک',
    languageAssistant: 'دستیار زبان',
    translateEasily: 'ترجمه و ارتباط آسان',
    eSIM: 'eSIM',
    stayConnected: 'متصل بمانید',
    payment: 'پرداخت',
    securePayment: 'گزینه‌های پرداخت امن',
    guide: 'راهنما',
    exploreLocal: 'کاوش جاذبه‌های محلی',
    emergency: 'اورژانس',
    quickEmergency: 'دسترسی سریع به خدمات اورژانسی',
    mapsNotSupported: 'نقشه‌ها در پیش‌نمایش وب Natively پشتیبانی نمی‌شوند',
    noAttractionsAvailable: 'جاذبه‌ای در دسترس نیست',
    // Nominative case (for selection lists)
    beijing: 'پکن',
    shanghai: 'شانگهای',
    hongKong: 'هنگ کنگ',
    hohhot: 'هوهوت',
    ordos: 'اوردوس',
    macao: 'ماکائو',
    // Dative case (for titles)
    beijingDative: 'پکن',
    shanghaiDative: 'شانگهای',
    hongKongDative: 'هنگ کنگ',
    hohhotDative: 'هوهوت',
    ordosDative: 'اوردوس',
    macaoDative: 'ماکائو',
    servicesDescription: 'دسترسی به خدمات ضروری برای سفر شما',
    essentialServices: 'خدمات ضروری',
    convenienceServices: 'خدمات راحتی',
    supportServices: 'خدمات پشتیبانی',
    currencyExchange: 'تبدیل ارز',
    convertCurrency: 'تبدیل آسان ارز',
    healthServices: 'خدمات بهداشتی',
    findMedicalHelp: 'یافتن کمک پزشکی در نزدیکی',
    accommodation: 'اقامتگاه',
    findPlaceToStay: 'یافتن محل اقامت',
    dining: 'غذا',
    discoverRestaurants: 'کشف رستوران‌های محلی',
    visaInfo: 'اطلاعات ویزا',
    visaRequirements: 'بررسی الزامات ویزا',
    onlineConsultation: 'مشاوره آنلاین',
    consultDoctorOnline: 'مشاوره با پزشکان آنلاین',
    buyMedicine: 'خرید دارو',
    orderMedicineOnline: 'سفارش دارو آنلاین',
    beijingProvince: 'پکن',
    shanghaiProvince: 'شانگهای',
    hongKongProvince: 'هنگ کنگ SAR',
    macaoProvince: 'ماکائو SAR',
    hohhotProvince: 'مغولستان داخلی',
    ordosProvince: 'مغولستان داخلی',
    theme: 'تم',
    autoTheme: 'خودکار',
    lightTheme: 'روشن',
    darkTheme: 'تاریک',
    autoThemeDescription: 'روشن در روز، تاریک در شب',
    lightThemeDescription: 'همیشه از تم روشن استفاده کنید',
    darkThemeDescription: 'همیشه از تم تاریک استفاده کنید',
    selectCityToViewInfo: 'برای مشاهده اطلاعات شهری را انتخاب کنید',
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  const [isRTL, setIsRTL] = useState(false);

  useEffect(() => {
    // Check if the selected language is RTL
    const rtlLanguages: SupportedLanguage[] = ['fa'];
    const shouldBeRTL = rtlLanguages.includes(language);
    
    // Only update if there's a change to avoid unnecessary re-renders
    if (shouldBeRTL !== isRTL) {
      setIsRTL(shouldBeRTL);
      
      // Force RTL layout for the entire app
      if (I18nManager.isRTL !== shouldBeRTL) {
        I18nManager.forceRTL(shouldBeRTL);
        // Note: On native platforms, this requires an app restart to take full effect
        console.log(`RTL mode ${shouldBeRTL ? 'enabled' : 'disabled'} for language: ${language}`);
      }
    }
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ t, language, setLanguage, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};
